[project]
name="inotives-cryptos-analytics"
version="0.1.0"
description='dbt transformations'
requires-python='>=3.12'
dependencies=[
    "dbt-core>=1.8.0",
    "dbt-postgres>=1.8.0",
]

[tool.uv]
package=false

[build-system]
requires=["hatchling"]
build-backend="hatchling.build"
